# Generated by Django 4.1.1 on 2022-09-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_rename_stock_item_stock"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="item_type",),
    ]
